#This is the main idea of this yaml file. YEET!

steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build Docker Image
  args:
  - 'build'
  - '.'
  - '-t'
  - 'grc.io/$PROJECT_ID/team1-api-test:latest'

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'grc.io/$PROJECT_ID/team1-api-test:latest'
  